### PR TITLE
Update for PHP 8.0

### LINKED ISSUE #1: PHP 8 support
I'll try and submit a PR, but just adding the request for this for now 🙂

### PR DESCRIPTION
**Pull request by manavo**
Closes #1

### CODE REVIEW

**Comment by Gemorroj** [comment]
thanks =)

**Comment by manavo** [comment]
Thanks! Sorry, I also just saw the read me needs updating too!

Also, any chance of a new tag? :)

**Comment by Gemorroj** [comment]
yes. most likely tomorrow

**Comment by manavo** [comment]
Great thanks! :)

**Pull request merged**
